=== Alinoss2910/AiramLinares_ExUD4-LMGSI/Ejercicio1/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:annotation>
  <xs:documentation xml:lang="Es-es">
    Esquema pedidos examen
    <fecha>14/02/2022</fecha>
    <autor>Airam Linares Ossorio</autor>
  </xs:documentation>
</xs:annotation>
<xs:element name="pedidos" type="pedidosDatos"/>
<xs:complexType name="pedidosDatos">
    <xs:sequence>
        <xs:element name="sucursal" type="sucursalDatos" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
</xs:complexType>
<xs:complexType name="sucursalDatos">
    <xs:sequence>
        <xs:element name="pedido" type="pedidoDatos" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="codigo" type="codigoTipo" use="required"/>
</xs:complexType>
<xs:complexType name="pedidoDatos">
    <xs:sequence>
        <xs:element name="NombreTrab" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="fechaPedido" type="xs:date"/>
        <xs:element name="observaciones" type="xs:string" minOccurs="0"/>
        <xs:element name="articulos" type="articuloDatos" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
<xs:simpleType name="codigoTipo">
    <xs:restriction base="xs:string">
        <xs:pattern value="[A-Za-z]([A-Za-z0-9]){7}"/>
    </xs:restriction>
</xs:simpleType>
<xs:complexType name="articuloDatos">
    <xs:sequence>
        <xs:element name="numeroUds">
            <xs:simpleType>
                <xs:restriction base="xs:positiveInteger">
                    <xs:minInclusive value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="pedido" type="PedidoDatos" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="codigo" type="codigoArticulo" use="required"/>
</xs:complexType>
<xs:simpleType name="codigoArticulo">
    <xs:restriction base="xs:string">
        <xs:pattern value="[A-Z]{3}-[0-9]{3}"/>
    </xs:restriction>
</xs:simpleType>
<xs:complexType name="PedidoDatos">
    <xs:sequence>
        <xs:element name="precio">
            <xs:simpleType>
                <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="obsevaciones" type="xs:string"/>
        <xs:element name="plazoRev">
            <xs:simpleType>
                <xs:restriction base="xs:positiveInteger">
                    <xs:minInclusive value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
    </xs:sequence>
</xs:complexType>
</xs:schema>

=== Alinoss2910/AiramLinares_ExUD4-LMGSI/Ejercicio1/pedidos_xsd.xml
<pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="pedidos.xsd">
    <sucursal codigo="A0000000">
        <pedido>
            <NombreTrab>Airam</NombreTrab>
            <fechaPedido>2022-06-20</fechaPedido>
            <observaciones>Urgente</observaciones>
            <articulos codigo="AAA-000">
                <numeroUds>2</numeroUds>
                <precio>15</precio>
                <obsevaciones></obsevaciones>
                <plazoRev>10</plazoRev>
            </articulos>
        </pedido>
    </sucursal>
</pedidos>
