=== Alinoss2910/AiramLinares_ExUD4-LMGSI/Ejercicio1/pedidos.dtd
<!ELEMENT pedidos (sucursal)>
<!ELEMENT sucursal (pedido)>
<!ATTLIST sucursal codigo NMTOKEN #REQUIRED>
<!ELEMENT pedido (NombreTrab,fechaPedido,observaciones,articulos)>
<!ELEMENT NombreTrab (#PCDATA)>
<!ELEMENT fechaPedido (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT articulos (numeroUds,precio,obsevaciones,plazoRev)>
<!ATTLIST articulos codigo NMTOKEN #REQUIRED>
<!ELEMENT numeroUds (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT obsevaciones EMPTY>
<!ELEMENT plazoRev (#PCDATA)>

=== Alinoss2910/AiramLinares_ExUD4-LMGSI/Ejercicio1/pedidos_dtd.xml
<!DOCTYPE pedidos SYSTEM "pedidos.dtd">
<pedidos>
    <sucursal codigo="A0000000">
        <pedido>
            <NombreTrab>Airam</NombreTrab>
            <fechaPedido>13-06-2022</fechaPedido>
            <observaciones>Urgente</observaciones>
            <articulos codigo="AAA-000">
                <numeroUds>2</numeroUds>
                <precio>15</precio>
                <obsevaciones></obsevaciones>
                <plazoRev>10</plazoRev>
            </articulos>
        </pedido>
    </sucursal>
</pedidos>
